development:
  adapter: mysql2
  host: localhost
  database: mephisto_development
  user: root

test:
  adapter: mysql2
  host: localhost
  database: mephisto_test
  user: root


production:
  adapter: mysql2
  host: localhost
  database: mephisto_production
  user: root
